### ISSUE TITLE
Error on "composer require cboden/ratchet"

### ISSUE THREAD

**Issue by hambern** [leocavalcante/oc-websockets#5]
I'm trying out your plugin on Homestead but I'm getting stuck already at `composer require cboden/ratchet`. The result I get is:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package cboden/ratchet ^0.3.5 is satisfiable by cboden/ratchet[v0.3.5, v0.3.6] but these conflict with your requirements or minimum-stability.
```

And I don't know what to do. If I go to my plugin folder, initiate composer and run `composer require cboden/ratchet` is seems to work. But not when I try to add it to the October CMS composer file. How do I solve this?

**Comment by leocavalcante** [comment]
Hi @Hambern 
Don't worry, you don't need to explicit require the dependency anymore.
October will already handle plugin dependencies.
Cheers.

**Comment by hambern** [comment]
Thank you. Saw that now :) The next problem is that I get the following error message when i run `php artisan websockets:run`:

`Method LeoCavalcante\WebSockets\Console\RunCommand::handle() does not exist`

Seems like it wants a handle-method that doesn't exist.

**Comment by hambern** [comment]
It seems to work if I add:

~~~php
public function handle()
    {
        $this->fire();
    }
~~~

to `LeoCavalcante\WebSockets\Console\RunCommand`

**Comment by Hambern** [comment]
But now I'm getting another error, sorry for making this a chat, but I think more people wonder the same things. After I now run `php artisan websockets:run` everything seems fine.

But if I add the component `[websocket]` I get another error:

`WebSocket connection to 'ws://localhost:8080/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
WrappedWebSocket @ VM565:164
init @ websocket.js?uri=ws%3A%2F%2Flocalhost%3A8080%2F:18
(anonymous) @ websocket.js?uri=ws%3A%2F%2Flocalhost%3A8080%2F:77
(anonymous) @ websocket.js?uri=ws%3A%2F%2Flocalhost%3A8080%2F:78
` in Chrome and

`WebSocket network error: The operation couldn’t be completed. Connection refused
3resetAnimation — f30e16ad70685e4909322d75c40b3060-1520466814:386` in Safari

But if I change the port to 8000 I get another error. But `http://localhost:8000` leads to a develop-webpage. So I guess that's why. It exists, but it's the wrong thing.

My setup is through Homestead on a VirtualBox on Mac. Could you just give me a hint in the right direction? :)

**Comment by leocavalcante** [comment]
Thanks for reporting, just updated to the new interface. Also, I could run a simple chat here, everything is working, but on any doubts don't mind to tell. Cheers.
